golang:
  - wrappers/golang/**/*.go
  - wrappers/golang/**/*.h
  - wrappers/golang/**/*.tmpl
  - go.mod
  - .github/workflows/golang.yml
cpp:
  - icicle/**/*.cu
  - icicle/**/*.cuh
  - icicle/**/*.cpp
  - icicle/**/*.hpp
  - icicle/**/*.c
  - icicle/**/*.h
  - icicle/CMakeLists.txt
  - icicle/cmake/**/*.cmake
  - .github/workflows/cpp.yml
